FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements-test.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements-test.txt

COPY . .

# CMD ["pytest", "-v"]
CMD ["sleep", "99999"]