version: '3'

services:
  smtp-tg-relay:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2548:25"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
